# pick our container
sudo: false
dist: trusty

# pick our language/runtime
language: python
python: '3.6'
cache: pip

# install our deps
install:
  - pip3 install pipenv
  - pipenv install

script: pipenv run bin/travis.sh
