name: Check dependencies and lint
on:
  push: {branches: [master]}
  pull_request:
jobs:
  check-deps-and-lint:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        uses: microsoft/action-python@0.7.2
        with:
          python_version: 3.7
          flake8: true
          fail_on_error: true
